### ISSUE TITLE
Wrong syntax highlighting

### ISSUE THREAD

**Issue by travankor** [orhun/kermit#12]
![2020-03-13-06:51:42PM](https://user-images.githubusercontent.com/38744110/76672784-97404b00-659f-11ea-958d-3eaf49ba001b.png)

Left one is `k3rmit`, right one is a different terminal. 
k3rmit has different syntax colors in neovim for some reason.

**Comment by orhun** [comment]
I've faced the same problem with vim today. Here's what I found about it: https://askubuntu.com/questions/46535/vim-black-text-on-black-background

Can you try `export TERM=xterm-color` before starting vim?

**Comment by travankor** [comment]
Nope, didn't fix it.

I wonder if this is related to the new vte3-0.60.0?

**Comment by orhun** [comment]
It might be about that. Currently I'm using 2.91 and everything is fine after the export command above. I'll keep looking for a solution.

**Comment by orhun** [comment]
`:set background=dark` didn't affect anything too, right?
how about `export TERM=xterm-256color`?

**Comment by travankor** [comment]
None of those worked.

**Comment by travankor** [comment]
Actually `:set background = dark` works

**Comment by orhun** [comment]
I'm not sure what does `:set background = dark` do but it's explained here: https://vi.stackexchange.com/questions/12104/what-does-set-background-dark-do

In this situation, it doesn't look like a solution for you.

**Comment by orhun** [comment]
256 colors are supported with the v3.0 release. This will fix the issue.
