### ISSUE TITLE
Vim launches with black screen.

### ISSUE THREAD

**Issue by opFez** [orhun/kermit#13]
Vim and Neovim both launches with a completely black screen, not showing the contents of the file I'm opening or anything else.

**Comment by orhun** [comment]
Can you give more information about the terminal version, VTE version, your vim config and OS details?

**Comment by opFez** [comment]
I'm using k3rmit version 2.3-1, VTE version 0.60.2-2.
I'm currently using https://github.com/nanotech/jellybeans.vim this color scheme and my .vimrc are in my dotfiles repository.
I'm using Arch Linux.

**Comment by orhun** [comment]
256 colors are supported with the v3.0 release. This will fix the issue.
