### ISSUE TITLE
Color difference

### ISSUE THREAD

**Issue by RossComputerGuy** [orhun/kermit#14]
I've found there's a color difference, in GIMP select the backgrounds color and they show to both be set as `#404522` but k3rmit is different than Urxvt. Is this a bug or is there a solution to fixing this in the config?
![Screenshot from 2020-05-18 01-17-46](https://user-images.githubusercontent.com/19699320/82190236-97154200-98a5-11ea-82ef-7dd05181dc41.png)

**Comment by orhun** [comment]
256 colors are supported with the v3.0 release. This will probably fix the issue.
