### ISSUE TITLE
Cursor shape option

### ISSUE THREAD

**Issue by ekickx** [orhun/kermit#15]
Will you add the option to change the cursor shape, for example like bar (|) or underscore(_)?

**Comment by orhun** [comment]
Yeah mayb--

It's added in the latest release. ([kermit.conf#L13](https://github.com/orhun/kermit/blob/2ab62236dd9842a8397b8e1d01fb6eff9f67e983/.config/kermit.conf#L13))

**Comment by ekickx** [comment]
Ohh cool. Thanks.
