### ISSUE TITLE
initial terminal size

### ISSUE THREAD

**Issue by disdaogitacc** [orhun/kermit#17]
set initial columns and rows values in config. i'm not sure whether it's implemented yet tho since couldn't find the setting in the default config file.
is it possible to accomplish this through gtk.css? or maybe in the source code?

edit: as a workaround in openbox WM i put these in rc.xml:
```
<application name="kermit*" class="*" type="normal">
    <size>      
        <height>538</height>      
        <width>958</width>
    </size>
</application>
```

regards
thank you.

**Comment by orhun** [comment]
Hello!

If it's about setting the width and height of the terminal on launch, it rather sounds like a window system issue to me. If it's not, please give me more details. 

Thanks.
